"""Core helpers for the desktop GUI pipeline integration."""

from __future__ import annotations

from .detection_io import (
    detection_json_path,
    load_detection_json,
    mask_dir_for_page,
    save_detection_json,
    save_detection_result,
)
from .detection_config import (
    DEFAULT_MANGA_MODEL_ID,
    DETECTION_ENGINE_CLASSIC,
    DETECTION_ENGINE_MANGA_RTDETR,
    DetectionConfig,
    detection_configs_match,
)
from .canon_state import (
    CANON_STATE_SCHEMA_VERSION,
    add_manual_canon_item,
    canon_item_bbox,
    canon_item_display_id,
    clamp_bbox_to_image,
    editor_category_for_kind,
    ensure_canon_state,
    get_active_canon_items,
    get_canon_item,
    is_valid_bbox,
    load_canon_state_for_page,
    manual_kind_for_editor_category,
    normalize_bbox,
    normalize_canon_kind,
    resolve_canon_item_for_stage_item,
    save_canon_state_for_page,
    set_canon_item_enabled,
    summarize_canon_state,
    update_canon_item_bbox,
)
from .detection_edit import (
    add_manual_detection_item,
    exclude_detection_item,
    load_detection_edit_items,
    save_detection_edit_items,
    summarize_detection_edit_state,
    update_detection_item_bbox,
)
from .detection_stage import run_detection_for_image
from .llama_server import LlamaServerManager, LlamaServerStatus
from .llama_cache import clear_llama_server_slots
from .inpaint_io import (
    bubble_mask_path,
    inpaint_image_path,
    inpaint_json_path,
    inpaint_preview_mask_path,
    load_inpaint_json,
    save_inpaint_json,
    summarize_inpaint_json,
    text_mask_path,
)
from .inpaint_stage import (
    get_lama_model_manager,
    load_lama_model,
    prepare_inpaint_mask_for_page,
    run_inpaint_for_page,
    run_inpaint_for_pages,
    unload_lama_model,
)
from .ocr_io import (
    load_ocr_json,
    normalize_ocr_item,
    ocr_crop_dir_for_page,
    ocr_json_path,
    save_ocr_payload,
    save_ocr_items_result,
    summarize_ocr_items,
    update_ocr_item_text,
)
from .ocr_models import (
    DEFAULT_LOCAL_OCR_PROVIDER,
    DEFAULT_OCR_PROVIDER,
    DEFAULT_OCR_PROVIDER_MODE,
    LOCAL_OCR_PROVIDER_CHOICES,
    OCR_PROVIDER_CHROME_LENS,
    OCR_PROVIDER_DEEPSEEK_OCR_LLAMA,
    OCR_PROVIDER_CHOICES,
    OCR_PROVIDER_MODE_CHOICES,
    OCR_PROVIDER_MODE_CHROME_LENS,
    OCR_PROVIDER_MODE_LOCAL,
    OCR_PROVIDER_PADDLE_VL_LLAMA,
    OCRConfig,
    normalize_local_ocr_provider,
    normalize_ocr_provider_name,
    normalize_ocr_provider_mode,
    provider_label,
    resolve_ocr_provider,
    selection_from_provider,
)
from .ocr_providers import (
    OCRProviderError,
    create_ocr_provider,
    validate_ocr_provider_config,
)
from .deepseek_ocr_client import (
    DEFAULT_MAX_TOKENS as DEEPSEEK_OCR_DEFAULT_MAX_TOKENS,
    DEFAULT_PROMPT as DEEPSEEK_OCR_DEFAULT_PROMPT,
    DEFAULT_TEMPERATURE as DEEPSEEK_OCR_DEFAULT_TEMPERATURE,
    DeepSeekOCRClient,
    DeepSeekOCRClientError,
)
from .ocr_edit import (
    exclude_ocr_item,
    load_ocr_edit_items,
    restore_ocr_item,
    save_ocr_edit_items,
    summarize_ocr_edit_state,
    update_ocr_item_bbox,
)
from .ocr_stage import prepare_ocr_items_for_image, run_ocr_for_page
from .chrome_lens_client import ChromeLensClient, ChromeLensClientError
from .render_io import (
    DEFAULT_RENDER_LINE_SPACING_RATIO,
    has_active_style_overrides,
    load_render_json,
    normalize_render_style_overrides,
    render_image_path,
    render_json_path,
    resolve_render_text,
    render_sprite_dir,
    save_render_json,
    summarize_render_json,
)
from .render_edit import (
    exclude_render_item,
    load_render_edit_items,
    restore_render_item,
    save_render_edit_items,
    summarize_render_edit_state,
    update_render_item_style_overrides,
    update_render_item_bbox,
)
from .render_models import RenderConfig
from .render_stage import (
    build_render_items_from_translation,
    prepare_render_for_page,
    run_render_for_page,
    run_render_for_pages,
)
from .render_styles import list_project_fonts, parse_color_value, resolve_font_path
from .process_stage import (
    PROCESS_PIPELINE_STEPS,
    PROCESS_STEP_KEYS,
    PROCESS_WORKFLOW_STAGE_BY_STEP,
    ProcessPageFailure,
    ProcessPipelineResult,
    ProcessStepDefinition,
    run_process_pipeline,
)
from .paddleocr_vl_client import (
    DEFAULT_PROMPT,
    PaddleOCRVLClient,
    PaddleOCRVLClientError,
)
from .translation_io import (
    initialize_translation_from_ocr,
    load_translation_json,
    normalize_translation_item,
    save_translation_json,
    summarize_translation_json,
    translation_json_path,
    update_translation_item_source_text,
    update_translation_item_translated_text,
)
from .translation_models import (
    LANGUAGE_CHOICES,
    OPENAI_COMPATIBLE_PRESET_BASE_URLS,
    OPENAI_COMPATIBLE_PRESET_CHOICES,
    OPENAI_COMPATIBLE_PRESET_CUSTOM,
    OPENAI_COMPATIBLE_PRESET_LM_STUDIO,
    OPENAI_COMPATIBLE_PRESET_LOCALAI,
    OPENAI_COMPATIBLE_PRESET_OPENAI,
    OPENAI_COMPATIBLE_PRESET_OPENROUTER,
    PROMPT_MODE_BUILT_IN_PLUS_USER,
    PROMPT_MODE_CHOICES,
    PROMPT_MODE_FULL_CUSTOM,
    STYLE_PROMPTS,
    TRANSLATOR_CHOICES,
    TranslationConfig,
    normalize_openai_compatible_preset,
    normalize_translator_name,
)
from .prompt_models import PromptBuildResult, PromptStyle
from .prompt_styles import BUILT_IN_PROMPT_STYLES, DEFAULT_PROMPT_STYLE_ID
from .prompt_studio import (
    build_prompt_preview,
    create_custom_style,
    default_output_contract,
    delete_custom_style,
    list_builtin_prompt_styles,
    normalize_custom_styles,
    normalize_prompt_mode,
    resolve_prompt_style,
)
from .translation_stage import (
    initialize_translation_for_page,
    run_translation_for_page,
    run_translation_for_pages,
    validate_translation_config,
)
from .export_io import (
    EXPORT_SCHEMA_VERSION,
    build_export_basename,
    ensure_export_dir,
    ensure_unique_path,
    export_manifest_path,
    export_zip_path,
    sanitize_windows_filename,
    save_export_manifest,
)
from .export_models import (
    DEFAULT_NAMING_PATTERN,
    EXPORT_SOURCE_CHOICES,
    OUTPUT_FORMAT_CHOICES,
    PAGE_SCOPE_CHOICES,
    ExportConfig,
)
from .export_stage import resolve_export_pages, run_export

__all__ = [
    "DEFAULT_NAMING_PATTERN",
    "DEFAULT_LOCAL_OCR_PROVIDER",
    "DEFAULT_OCR_PROVIDER",
    "DEFAULT_OCR_PROVIDER_MODE",
    "EXPORT_SCHEMA_VERSION",
    "EXPORT_SOURCE_CHOICES",
    "LOCAL_OCR_PROVIDER_CHOICES",
    "OUTPUT_FORMAT_CHOICES",
    "PAGE_SCOPE_CHOICES",
    "CANON_STATE_SCHEMA_VERSION",
    "DEFAULT_MANGA_MODEL_ID",
    "detection_json_path",
    "DETECTION_ENGINE_CLASSIC",
    "DETECTION_ENGINE_MANGA_RTDETR",
    "DetectionConfig",
    "detection_configs_match",
    "add_manual_canon_item",
    "add_manual_detection_item",
    "canon_item_bbox",
    "canon_item_display_id",
    "clamp_bbox_to_image",
    "load_ocr_json",
    "load_ocr_edit_items",
    "load_translation_json",
    "load_detection_json",
    "load_detection_edit_items",
    "load_canon_state_for_page",
    "DEFAULT_PROMPT",
    "DEFAULT_PROMPT_STYLE_ID",
    "LANGUAGE_CHOICES",
    "LlamaServerManager",
    "LlamaServerStatus",
    "clear_llama_server_slots",
    "OPENAI_COMPATIBLE_PRESET_BASE_URLS",
    "OPENAI_COMPATIBLE_PRESET_CHOICES",
    "OPENAI_COMPATIBLE_PRESET_CUSTOM",
    "OPENAI_COMPATIBLE_PRESET_LM_STUDIO",
    "OPENAI_COMPATIBLE_PRESET_LOCALAI",
    "OPENAI_COMPATIBLE_PRESET_OPENAI",
    "OPENAI_COMPATIBLE_PRESET_OPENROUTER",
    "OCRConfig",
    "OCRProviderError",
    "OCR_PROVIDER_CHROME_LENS",
    "OCR_PROVIDER_DEEPSEEK_OCR_LLAMA",
    "OCR_PROVIDER_CHOICES",
    "OCR_PROVIDER_MODE_CHOICES",
    "OCR_PROVIDER_MODE_CHROME_LENS",
    "OCR_PROVIDER_MODE_LOCAL",
    "OCR_PROVIDER_PADDLE_VL_LLAMA",
    "DEEPSEEK_OCR_DEFAULT_MAX_TOKENS",
    "DEEPSEEK_OCR_DEFAULT_PROMPT",
    "DEEPSEEK_OCR_DEFAULT_TEMPERATURE",
    "DeepSeekOCRClient",
    "DeepSeekOCRClientError",
    "PROMPT_MODE_BUILT_IN_PLUS_USER",
    "PROMPT_MODE_CHOICES",
    "PROMPT_MODE_FULL_CUSTOM",
    "PromptBuildResult",
    "PromptStyle",
    "ExportConfig",
    "BUILT_IN_PROMPT_STYLES",
    "bubble_mask_path",
    "build_prompt_preview",
    "build_export_basename",
    "create_custom_style",
    "default_output_contract",
    "delete_custom_style",
    "ensure_export_dir",
    "ensure_unique_path",
    "export_manifest_path",
    "export_zip_path",
    "get_lama_model_manager",
    "get_active_canon_items",
    "get_canon_item",
    "inpaint_image_path",
    "inpaint_json_path",
    "inpaint_preview_mask_path",
    "load_inpaint_json",
    "load_lama_model",
    "mask_dir_for_page",
    "normalize_bbox",
    "normalize_ocr_item",
    "normalize_canon_kind",
    "normalize_custom_styles",
    "normalize_openai_compatible_preset",
    "normalize_local_ocr_provider",
    "normalize_prompt_mode",
    "normalize_ocr_provider_mode",
    "normalize_translation_item",
    "normalize_translator_name",
    "ocr_crop_dir_for_page",
    "ocr_json_path",
    "PaddleOCRVLClient",
    "PaddleOCRVLClientError",
    "ChromeLensClient",
    "ChromeLensClientError",
    "DEFAULT_RENDER_LINE_SPACING_RATIO",
    "RenderConfig",
    "has_active_style_overrides",
    "render_image_path",
    "render_json_path",
    "render_sprite_dir",
    "resolve_render_text",
    "resolve_font_path",
    "resolve_prompt_style",
    "list_project_fonts",
    "list_builtin_prompt_styles",
    "parse_color_value",
    "PROCESS_PIPELINE_STEPS",
    "PROCESS_STEP_KEYS",
    "PROCESS_WORKFLOW_STAGE_BY_STEP",
    "prepare_ocr_items_for_image",
    "prepare_inpaint_mask_for_page",
    "prepare_render_for_page",
    "ProcessPageFailure",
    "ProcessPipelineResult",
    "ProcessStepDefinition",
    "run_inpaint_for_page",
    "run_inpaint_for_pages",
    "run_process_pipeline",
    "run_render_for_page",
    "run_render_for_pages",
    "STYLE_PROMPTS",
    "TRANSLATOR_CHOICES",
    "TranslationConfig",
    "translation_json_path",
    "initialize_translation_from_ocr",
    "initialize_translation_for_page",
    "run_translation_for_page",
    "run_translation_for_pages",
    "run_ocr_for_page",
    "create_ocr_provider",
    "run_detection_for_image",
    "run_export",
    "resolve_export_pages",
    "build_render_items_from_translation",
    "sanitize_windows_filename",
    "save_ocr_payload",
    "save_canon_state_for_page",
    "save_ocr_edit_items",
    "save_export_manifest",
    "save_inpaint_json",
    "save_ocr_items_result",
    "save_render_json",
    "save_render_edit_items",
    "save_translation_json",
    "save_detection_result",
    "save_detection_json",
    "save_detection_edit_items",
    "load_render_json",
    "load_render_edit_items",
    "normalize_render_style_overrides",
    "exclude_detection_item",
    "exclude_ocr_item",
    "exclude_render_item",
    "summarize_inpaint_json",
    "summarize_canon_state",
    "summarize_detection_edit_state",
    "summarize_ocr_edit_state",
    "summarize_ocr_items",
    "summarize_render_edit_state",
    "summarize_render_json",
    "summarize_translation_json",
    "text_mask_path",
    "unload_lama_model",
    "update_canon_item_bbox",
    "update_detection_item_bbox",
    "update_ocr_item_bbox",
    "update_ocr_item_text",
    "update_render_item_bbox",
    "update_render_item_style_overrides",
    "update_translation_item_source_text",
    "update_translation_item_translated_text",
    "validate_ocr_provider_config",
    "validate_translation_config",
    "provider_label",
    "restore_ocr_item",
    "restore_render_item",
    "editor_category_for_kind",
    "ensure_canon_state",
    "is_valid_bbox",
    "manual_kind_for_editor_category",
    "normalize_ocr_provider_name",
    "resolve_canon_item_for_stage_item",
    "resolve_ocr_provider",
    "selection_from_provider",
    "set_canon_item_enabled",
]
